import subprocess

__author__ ='John Möller'


def check(string, debug=False, return_valid_asignment=False):
    """Checks if a formula generated by the generate_formula method,
    can be satisfied or not.
    """
    if debug:
        result =subprocess.check_output(["python", "simple-sat/src/sat.py","-v", "-ti", string])
        return result
    if return_valid_asignment:
        result = subprocess.check_output(["python", "simple-sat/src/sat.py", "-ti", string])
        return result
    else:
        result =subprocess.check_output(["python", "simple-sat/src/sat.py", "-ti", string])
        if result == "" or result == b'':
            # print ('result =', [result])
            return 0
        else:
            # print ('result=', [result])
            return 1


def generate_formula(seed, debug=False):
    """Generates a formula that can checked with the check function.
    """
    digits = seed
    formula = []
    disjunction_counter  = 0

    for digit in digits:
        if disjunction_counter % 3 == 0 and disjunction_counter != 0:
            formula.append(",")
            formula.append(" ")
        if int(digit)<5 :
            formula.append(str(digit))
            formula.append(" " )
            if debug:
                print ("borde vara under 5: " + str(digit))
        else:
            formula.append("~")
            formula.append(str(int(digit)-5))
            formula.append(" ")
            if debug:
                print ("borde vara over 5: "+ str(digit))
        if debug:
            print ("formula: ", formula)
        disjunction_counter += 1

    return "".join(formula)


def main():
    counter_example = [0,0,0,5,5,5]
    number = 123678173
    number2 = 123479872359201234
    stuff =generate_formula(counter_example)

    print ("Seed: ", counter_example)
    print (stuff)
    print ("Validity: ", check(stuff, debug=False, return_valid_asignment=False))


if __name__ == '__main__':
     main()



